# Generated by Django 6.0 on 2026-01-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_publicacion', models.DateField()),
                ('autor', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
